Resources:
  GroceryListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "date"
          AttributeType: "S"
        - AttributeName: "items"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "date"
          KeyType: "HASH"
        - AttributeName: "items"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "GroceryList"